### PR TITLE
Use ILCompiler from nuget.org

### PR DESCRIPTION
**Pull request by nifanfa**
The ILCompiler on dotnet-experiment is not available anymore...

### CODE REVIEW

**Comment by nifanfa** [comment]
```diff
-    <PackageReference Include="Microsoft.DotNet.ILCompiler" Version="7.0.0-*" />
+    <PackageReference Include="Microsoft.DotNet.ILCompiler" Version="7.0.0-preview.2.22152.2" />
```
we can't use the latest version because the latest version will not compile zerosharp to native apps

**Comment by MichalStrehovsky** [comment]
What's the exception/stacktrace you're seeing with latest? It can probably be worked around. (I can figure it out myself but likely won't be at a computer for a day or two, just my phone)

**Comment by MichalStrehovsky** [comment]
Try adding `<PublishAot>true</PublishAot>`

**Comment by nifanfa** [comment]
> Try adding `<PublishAot>true</PublishAot>`

that still not working. nothing would happen

**Comment by nifanfa** [comment]
> What's the exception/stacktrace you're seeing with latest? It can probably be worked around. (I can figure it out myself but likely won't be at a computer for a day or two, just my phone)

Just nothing happens. It has the same effect without the package

**Comment by MichalStrehovsky** [comment]
https://github.com/MichalStrehovsky/zerosharp/pull/37 updated things to. NET 7

**Pull request closed without merging**
